#!/usr/bin/env zsh

echo "Checking for SSH key, generating one if it doesn't exist ..."
  [[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa

echo "Copying public key to clipboard. Paste it into your Github account ..."
  [[ -f ~/.ssh/id_rsa.pub ]] && cat ~/.ssh/id_rsa.pub | pbcopy
  open https://github.com/account/ssh

echo "Installing Alcatraz, the Xcode Package Manager ..."
  mkdir -p ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins;
  curl -L http://goo.gl/xfmmt | tar xv -C ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins -

echo "Installing RVM (Ruby Version Manager) ..."
  curl -L https://get.rvm.io | bash -s stable --ruby
  echo "
# RVM
[[ -s '/Users/`whoami`/.rvm/scripts/rvm' ]] && source '/Users/`whoami`/.rvm/scripts/rvm'" >> ~/.zshrc
  source ~/.zshrc

zsh < <(curl -s https://raw.github.com/JJSaccolo/The-Setup/master/ruby)

echo "Installing Homebrew, a good OS X package manager ..."
  ruby <(curl -fsS https://raw.github.com/mxcl/homebrew/go)
  brew update

echo "Put Homebrew location earlier in PATH ..."
  echo "
# recommended by brew doctor
export PATH='/usr/local/bin:$PATH'" >> ~/.zshrc
  source ~/.zshrc

echo "Installing MySQL, the most popular RDBMS ..."
  brew install mysql

echo "Installing Postgres, a good open source relational database ..."
  brew install postgres --no-python

echo "Installing MongoDB, a very good NoSQL DBMS ..."
  brew install mongodb

echo -n "Your git name: "
  git config --global user.name
echo -n "Your git email: "
  git config --global user.email
echo "Change these with \ngit config --global user.name \"Your Name\" \ngit config --global user.email your@email.com"
